# Generated by Django 5.1.15 on 2026-06-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('contract_type', models.CharField(choices=[('wedding', 'Wedding'), ('events', 'Events'), ('real_estate', 'Real estate'), ('commercial', 'Commercial'), ('model_release', 'Model release')], default='wedding', max_length=16)),
                ('body', models.TextField(help_text='May contain {{client_name}}, {{business_name}}, {{event_date}}, {{total}}')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('client_signature_name', models.CharField(blank=True, max_length=160)),
                ('signed_by_client_at', models.DateTimeField(blank=True, null=True)),
                ('creative_signature_name', models.CharField(blank=True, max_length=160)),
                ('signed_by_creative_at', models.DateTimeField(blank=True, null=True)),
                ('audit', models.JSONField(blank=True, default=list)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bookings.booking')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
