# Generated by Django 5.1.15 on 2026-06-07 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('suburb', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(default='Melbourne', max_length=80)),
                ('state', models.CharField(default='VIC', max_length=8)),
                ('service_radius_km', models.PositiveIntegerField(default=40)),
                ('primary_category', models.CharField(choices=[('weddings', 'Weddings'), ('events', 'Events'), ('real-estate', 'Real Estate'), ('business', 'Business & Brand'), ('family', 'Family & Portrait'), ('content', 'Content & Reels')], default='weddings', max_length=20)),
                ('styles', models.CharField(blank=True, help_text='Comma-separated style tags', max_length=200)),
                ('equipment', models.CharField(blank=True, max_length=200)),
                ('languages', models.CharField(blank=True, default='English', max_length=120)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('response_time_hours', models.PositiveIntegerField(default=24)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('accent', models.CharField(choices=[('navy', 'Navy'), ('teal', 'Teal'), ('sky', 'Sky')], default='navy', max_length=8)),
                ('is_featured', models.BooleanField(default=False)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('weddings', 'Weddings'), ('events', 'Events'), ('real-estate', 'Real Estate'), ('business', 'Business & Brand'), ('family', 'Family & Portrait'), ('content', 'Content & Reels')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('inclusions', models.TextField(blank=True, help_text='One inclusion per line')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='profiles.service')),
            ],
            options={
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('abn', 'ABN / business'), ('insurance', 'Public liability insurance'), ('wwcc', 'Working With Children Check'), ('id', 'Identity')], max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='verification/')),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('booked', 'Booked')], default='available', max_length=12)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('workspace', 'date')},
            },
        ),
    ]
