# Generated by Django 5.1.15 on 2026-06-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creativeprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
