# Generated by Django 5.1.15 on 2026-06-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_creativeprofile_latitude_creativeprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeprofile',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
