# Generated by Django 5.1.15 on 2026-06-07 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('gallery_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=6)),
                ('visibility', models.CharField(choices=[('private', 'Private (logged-in client)'), ('password', 'Password protected')], default='private', max_length=10)),
                ('access_code', models.CharField(blank=True, max_length=40)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='bookings.booking')),
            ],
            options={
                'verbose_name_plural': 'galleries',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='galleries/')),
                ('video_url', models.URLField(blank=True)),
                ('asset_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video link')], default='photo', max_length=6)),
                ('accent', models.CharField(choices=[('navy', 'Navy'), ('teal', 'Teal'), ('sky', 'Sky')], default='navy', max_length=8)),
                ('is_favourite', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='galleries.gallery')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
