# Generated by Django 5.1.15 on 2026-06-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='delivery_url',
            field=models.URLField(blank=True),
        ),
    ]
