# Generated by Django 5.1.15 on 2026-06-08 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('backup', 'Back up & import'), ('cull', 'Cull & select'), ('sneak_peek', 'Sneak peek'), ('send_to_editor', 'Send to editor'), ('editor_return', 'Editor return'), ('editing', 'Editing'), ('proofing', 'Client proofing'), ('album', 'Album design'), ('final_delivery', 'Final gallery delivery'), ('final_payment', 'Final payment due'), ('archive', 'Archive & cleanup')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_client_facing', models.BooleanField(default=False)),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=2)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='bookings.booking')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['due_date', 'sort_order'],
            },
        ),
    ]
