# Generated by Django 5.1.15 on 2026-06-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='kind',
            field=models.CharField(choices=[('backup', 'Back up & import'), ('cull', 'Cull & select'), ('sneak_peek', 'Sneak peek'), ('send_to_editor', 'Send to editor'), ('editor_return', 'Editor return'), ('editing', 'Editing'), ('proofing', 'Client proofing'), ('album', 'Album design'), ('final_delivery', 'Final gallery delivery'), ('final_payment', 'Final payment due'), ('archive', 'Archive & cleanup'), ('custom', 'Task')], max_length=20),
        ),
        migrations.CreateModel(
            name='DeliverableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('day_offset', models.IntegerField(default=7, help_text="Days after the shoot date it's due")),
                ('is_client_facing', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['sort_order', 'day_offset', 'id'],
            },
        ),
    ]
