# Generated by Django 5.1.15 on 2026-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
