# Generated by Django 5.1.15 on 2026-06-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_refunded_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
