# Generated by Django 5.1.15 on 2026-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('shoot', 'Shoot'), ('editing_due', 'Editing due'), ('payment_due', 'Payment due'), ('contract_due', 'Contract due'), ('blocked', 'Blocked'), ('custom', 'Personal')], default='shoot', max_length=14),
        ),
    ]
